import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Kalnia_Glaze,
  Kanit,
  Poppins,
} from "next/font/google";
import "./globals.css";
import SessionWrapper from "@/components/SessionWrapper";
import { Toaster } from "@/components/ui/toaster";
import { LoadingProvider } from "@/context/loadingContext";
import { AddContentModalProvider } from "@/context/AddContentContext";
import { InteractingAiModalProvider } from "@/context/AiInteractionContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const kalniaGlaze = Kalnia_Glaze({
  variable: "--font-kalnia-glaze",
  subsets: ["latin"],
  weight: ["100", "400", "700"],
});

const kanit = Kanit({
  variable: "--font-kanit",
  subsets: ["latin"],
  weight: ["100", "400", "700"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "400", "700"],
});

export const metadata: Metadata = {
  title: "link management app",
  description: "Generated by love from gaurav",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${kalniaGlaze.variable} ${kanit.variable} ${poppins.variable} antialiased`}
      >
        <SessionWrapper>
          <InteractingAiModalProvider>
            <LoadingProvider>
              <AddContentModalProvider>{children}</AddContentModalProvider>
            </LoadingProvider>
          </InteractingAiModalProvider>
        </SessionWrapper>
        <Toaster />
      </body>
    </html>
  );
}
